version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
    command: bash -c "python main.py"
    container_name: wycm_web
    env_file:
      - prod.env
    restart: always
    ports:
      - "3052:3052"
