version: "2.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    command: /bin/sh -c "scripts/start.sh"

    container_name: grank_web
    env_file:
      - prod.env
    restart: always
    ports:
      - "80:3052"
