"""add grdae, ispublic field to github user

Revision ID: 0471d04592b7
Revises: 826ed2f2e8e4
Create Date: 2021-07-06 07:09:32.884711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0471d04592b7'
down_revision = '826ed2f2e8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_user', sa.Column('grade', sa.Integer(), nullable=False))
    op.add_column('github_user', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_user', 'is_public')
    op.drop_column('github_user', 'grade')
    # ### end Alembic commands ###
