"""add columns to github user

Revision ID: 0ffacc1890b3
Revises: 04a9e0a7d1d3
Create Date: 2021-06-24 00:12:38.013989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ffacc1890b3"
down_revision = "04a9e0a7d1d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("github_user", sa.Column("is_approved", sa.Boolean(), nullable=False))
    op.alter_column("github_user", "username", existing_type=sa.VARCHAR(length=256), nullable=False)
    op.create_unique_constraint(None, "github_user", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "github_user", type_="unique")
    op.alter_column("github_user", "username", existing_type=sa.VARCHAR(length=256), nullable=True)
    op.drop_column("github_user", "is_approved")
    # ### end Alembic commands ###
