"""delete social authentication and add user

Revision ID: c5623a277f90
Revises: f482d22cb32e
Create Date: 2021-07-05 14:25:32.518026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5623a277f90'
down_revision = 'f482d22cb32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('social_authentication')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_authentication',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sns_service_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='social_authentication_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
