"""add avatar url field

Revision ID: d23626fcf0c2
Revises: 44e63ebd37dc
Create Date: 2021-06-30 06:07:11.199738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23626fcf0c2'
down_revision = '44e63ebd37dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['id'])
    op.create_unique_constraint(None, 'admin_certification_code', ['code'])
    op.add_column('github_user', sa.Column('avatar_url', sa.String(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_user', 'avatar_url')
    op.drop_constraint(None, 'admin_certification_code', type_='unique')
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
