"""create social authentication table

Revision ID: f482d22cb32e
Revises: d23626fcf0c2
Create Date: 2021-07-05 06:33:06.280089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f482d22cb32e'
down_revision = 'd23626fcf0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_authentication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sns_service_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_authentication')
    # ### end Alembic commands ###
